### ISSUE TITLE
Changing directory into a tag/commit takes a long time

### ISSUE THREAD

**Issue by dspinellis** [AUEB-BALab/RepoFS#12]
There is no good reason it should take 6s for such an operation.  Example:
```
root@snf-800019:~/unix-history/tags/FreeBSD-release# time cd 1.1

real    0m6.095s
user    0m0.000s
sys     0m0.000s
```

**Comment by VitSalis** [comment]
This happens because repofs needs to load the commits of the date the commit pointed by the tag was created. Loading the commits of a specific date is a costly operation since we use regular Git commands instead of pygit2.

**Comment by dspinellis** [comment]
Why does it need to load the dates at that point? It shouldn't. I would expect it to do that when you do an *ls* in the `commits-by-date` directory.

**Comment by VitSalis** [comment]
It loads the dates at that point because the tag links to a commit hash directory stored under `commits-by-date`. The commit hashes for date `yyyy-mm-dd` are only loaded when you access the directory `commits-by-date/yyyy/mm/dd`, which happens in this case because of the link.

When you do an _ls_ in the `commits-by-date` directory the filesystem loads only what it needs to, in this case the years.

**Comment by dspinellis** [comment]
Right!  Should we lazy link them to `tags-by-hash`?  (Without retrieving all hashes.)

**Comment by VitSalis** [comment]
I linked them to `commits-by-hash` since we retrieve all the hashes anyway, so they're cached.
I did that in commit 58d137a914c382feb7bddb18473766c812b9aad4 and the performance seems to be improved.

**Comment by dspinellis** [comment]
:+1:
