### ISSUE TITLE
Set commit directory creation/modification from commit's timestamp

### ISSUE THREAD

**Issue by dspinellis** [AUEB-BALab/RepoFS#9]
Creation time can be author commit time and modification time can be commit time.

**Comment by VitSalis** [comment]
Fixed by c15cf0ad9ad8cb622cb951447a2b3ea481ee8426

This commit sets the creation and modification time as the commit time. I didn't set the creation time as the author commit time, because pygit doesn't provide support for getting the author commit time. Retrieving it manually would slow the system down, since the creation time is set on `getattr` which is called for every file/directory in the repository.
